
export const TOGGLE_PROBLEM = 'TOGGLE_PROBLEM';
export type TOGGLE_PROBLEM = typeof TOGGLE_PROBLEM;

export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export type RECEIVE_USER_DATA = typeof RECEIVE_USER_DATA;

export const RECEIVE_SCOREBOARD_DATA = 'RECEIVE_SCOREBOARD_DATA';
export type RECEIVE_SCOREBOARD_DATA = typeof RECEIVE_SCOREBOARD_DATA;

export const RECEIVE_SCOREBOARD_ITEM = 'RECEIVE_SCOREBOARD_ITEM';
export type RECEIVE_SCOREBOARD_ITEM = typeof RECEIVE_SCOREBOARD_ITEM;

export const RECEIVE_CONTEST = 'RECEIVE_CONTEST';
export type RECEIVE_CONTEST = typeof RECEIVE_CONTEST;

export const UPDATE_SCOREBOARD_TIMER = 'UPDATE_SCOREBOARD_TIMER';
export type UPDATE_SCOREBOARD_TIMER = typeof UPDATE_SCOREBOARD_TIMER;

export const SORT_PROBLEMS = 'SORT_PROBLEMS';
export type SORT_PROBLEMS = typeof SORT_PROBLEMS;

export const BY_NUMBER = 'BY_NUMBER';
export const BY_POINTS = 'BY_POINTS';
