ALTER TABLE `comp_class`
    CHANGE COLUMN `time_begin` `time_begin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN `time_end` `time_end` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `contender`
    CHANGE COLUMN `name` `name` VARCHAR(64) NULL,
    CHANGE COLUMN `class_id` `class_id` INT NULL,
    CHANGE COLUMN `entered` `entered` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `tick`
    CHANGE COLUMN `timestamp` `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;