package se.scoreboard.data.domain

// Generated Feb 3, 2019 9:58:01 PM by Hibernate Tools 5.2.11.Final

import java.util.*
import javax.persistence.*
import javax.persistence.GenerationType.IDENTITY

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color")
class Color : java.io.Serializable {

    @get:Id
    @get:GeneratedValue(strategy = IDENTITY)
    @get:Column(name = "id", unique = true, nullable = false)
    var id: Int? = null

    @get:Column(name = "name", nullable = false, length = 32)
    var name: String? = null

    @get:Column(name = "red", nullable = false)
    var red: Byte = 0

    @get:Column(name = "green", nullable = false)
    var green: Byte = 0

    @get:Column(name = "blue", nullable = false)
    var blue: Byte = 0

    @get:OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
    var problems: Set<Problem> = HashSet(0)

    constructor()

    constructor(name: String, red: Byte, green: Byte, blue: Byte) {
        this.name = name
        this.red = red
        this.green = green
        this.blue = blue
    }

    constructor(name: String, red: Byte, green: Byte, blue: Byte, problems: Set<Problem>) {
        this.name = name
        this.red = red
        this.green = green
        this.blue = blue
        this.problems = problems
    }

}
