package se.scoreboard.data.domain

// Generated Feb 3, 2019 9:58:01 PM by Hibernate Tools 5.2.11.Final

import java.util.*
import javax.persistence.*
import javax.persistence.GenerationType.IDENTITY

/**
 * Contest generated by hbm2java
 */
@Entity
@Table(name = "contest")
class Contest : java.io.Serializable {

    @get:Id
    @get:GeneratedValue(strategy = IDENTITY)
    @get:Column(name = "id", unique = true, nullable = false)
    var id: Int? = null
    @get:ManyToOne(fetch = FetchType.LAZY)
    @get:JoinColumn(name = "location_id", nullable = false)
    var location: Location? = null
    @get:ManyToOne(fetch = FetchType.LAZY)
    @get:JoinColumn(name = "organizer_id", nullable = false)
    var organizer: Organizer? = null
    @get:Column(name = "name", nullable = false, length = 64)
    var name: String? = null
    @get:Column(name = "description", length = 65535)
    var description: String? = null
    @get:Column(name = "qualifying_problems", nullable = false)
    var qualifyingProblems: Int = 0
    @get:OneToMany(fetch = FetchType.LAZY, mappedBy = "contest")
    var problems: Set<Problem> = HashSet(0)
    @get:OneToMany(fetch = FetchType.LAZY, mappedBy = "contest")
    var contenders: Set<Contender> = HashSet(0)

    constructor()

    constructor(location: Location, organizer: Organizer, name: String, qualifyingProblems: Int) {
        this.location = location
        this.organizer = organizer
        this.name = name
        this.qualifyingProblems = qualifyingProblems
    }

    constructor(location: Location, organizer: Organizer, name: String, description: String, qualifyingProblems: Int,
                problems: Set<Problem>, contenders: Set<Contender>) {
        this.location = location
        this.organizer = organizer
        this.name = name
        this.description = description
        this.qualifyingProblems = qualifyingProblems
        this.problems = problems
        this.contenders = contenders
    }

}
