package se.scoreboard.data.domain

// Generated Feb 3, 2019 9:58:01 PM by Hibernate Tools 5.2.11.Final

import java.util.*
import javax.persistence.*
import javax.persistence.GenerationType.IDENTITY

/**
 * Contender generated by hbm2java
 */
@Entity
@Table(name = "contender", uniqueConstraints = arrayOf(UniqueConstraint(columnNames = arrayOf("registration_code"))))
class Contender : java.io.Serializable {

    @get:Id
    @get:GeneratedValue(strategy = IDENTITY)
    @get:Column(name = "id", unique = true, nullable = false)
    var id: Int? = null

    @get:ManyToOne(fetch = FetchType.LAZY)
    @get:JoinColumn(name = "contest_id", nullable = false)
    var contest: Contest? = null

    @get:Column(name = "registration_code", unique = true, nullable = false, length = 16)
    var registrationCode: String? = null

    @get:Column(name = "name", nullable = false, length = 64)
    var name: String? = null

    @get:Column(name = "class_id", nullable = false)
    var classId: Int = 0

    @get:Temporal(TemporalType.TIMESTAMP)
    @get:Column(name = "entered", length = 26)
    var entered: Date? = null

    @get:OneToMany(fetch = FetchType.LAZY, mappedBy = "contender")
    var ticks: Set<Tick> = HashSet(0)

    constructor()

    constructor(contest: Contest, registrationCode: String, name: String, classId: Int) {
        this.contest = contest
        this.registrationCode = registrationCode
        this.name = name
        this.classId = classId
    }

    constructor(contest: Contest, registrationCode: String, name: String, classId: Int, entered: Date,
                ticks: Set<Tick>) {
        this.contest = contest
        this.registrationCode = registrationCode
        this.name = name
        this.classId = classId
        this.entered = entered
        this.ticks = ticks
    }

}
