package se.scoreboard.data.domain

// Generated Feb 3, 2019 9:58:01 PM by Hibernate Tools 5.2.11.Final

import java.util.*
import javax.persistence.*
import javax.persistence.GenerationType.IDENTITY

/**
 * Problem generated by hbm2java
 */
@Entity
@Table(name = "problem")
class Problem : java.io.Serializable {

    @get:Id
    @get:GeneratedValue(strategy = IDENTITY)
    @get:Column(name = "id", unique = true, nullable = false)
    var id: Int? = null

    @get:ManyToOne(fetch = FetchType.LAZY)
    @get:JoinColumn(name = "color_id", nullable = false)
    var color: Color? = null

    @get:ManyToOne(fetch = FetchType.LAZY)
    @get:JoinColumn(name = "contest_id", nullable = false)
    var contest: Contest? = null

    @get:Column(name = "number", nullable = false)
    var number: Int = 0

    @get:Column(name = "points", nullable = false)
    var points: Int = 0

    @get:Column(name = "flash_bonus")
    var flashBonus: Int? = null

    @get:OneToMany(fetch = FetchType.LAZY, mappedBy = "problem")
    var ticks: Set<Tick> = HashSet(0)

    constructor()

    constructor(color: Color, contest: Contest, number: Int, points: Int) {
        this.color = color
        this.contest = contest
        this.number = number
        this.points = points
    }

    constructor(color: Color, contest: Contest, number: Int, points: Int, flashBonus: Int?, ticks: Set<Tick>) {
        this.color = color
        this.contest = contest
        this.number = number
        this.points = points
        this.flashBonus = flashBonus
        this.ticks = ticks
    }

}
