package se.scoreboard.data.domain

// Generated Feb 3, 2019 9:58:01 PM by Hibernate Tools 5.2.11.Final

import java.util.*
import javax.persistence.*
import javax.persistence.GenerationType.IDENTITY

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", uniqueConstraints = arrayOf(UniqueConstraint(columnNames = arrayOf("email"))))
class User : java.io.Serializable {

    @get:Id
    @get:GeneratedValue(strategy = IDENTITY)
    @get:Column(name = "id", unique = true, nullable = false)
    var id: Int? = null
    @get:Column(name = "name", nullable = false, length = 32)
    var name: String? = null
    @get:Column(name = "email", unique = true, nullable = false, length = 64)
    var email: String? = null
    @get:Column(name = "password", nullable = false, length = 60)
    var password: String? = null
    @get:ManyToMany(fetch = FetchType.LAZY)
    @get:JoinTable(name = "user_organizer", catalog = "scoreboard", joinColumns = arrayOf(JoinColumn(name = "user_id", nullable = false, updatable = false)), inverseJoinColumns = arrayOf(JoinColumn(name = "organizer_id", nullable = false, updatable = false)))
    var organizers: Set<Organizer> = HashSet(0)

    constructor()

    constructor(name: String, email: String, password: String) {
        this.name = name
        this.email = email
        this.password = password
    }

    constructor(name: String, email: String, password: String, organizers: Set<Organizer>) {
        this.name = name
        this.email = email
        this.password = password
        this.organizers = organizers
    }

}
