-- MySQL Script generated by MySQL Workbench
-- mån 26 feb 2024 19:23:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scoreboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `homepage` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_series_1`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `organizer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_series_1` ON `series` (`organizer_id` ASC);

CREATE INDEX `index3` ON `series` (`id` ASC, `organizer_id` ASC);


-- -----------------------------------------------------
-- Table `contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `protected` TINYINT(1) NOT NULL DEFAULT 0,
  `series_id` INT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `location` VARCHAR(1024) NULL,
  `final_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `qualifying_problems` INT NOT NULL,
  `finalists` INT NOT NULL,
  `rules` TEXT NULL,
  `grace_period` INT NOT NULL DEFAULT 300,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contest_2`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `organizer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_contest_3`
    FOREIGN KEY (`series_id` , `organizer_id`)
    REFERENCES `series` (`id` , `organizer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_contest_2_idx` ON `contest` (`organizer_id` ASC);

CREATE INDEX `fk_contest_3` ON `contest` (`series_id` ASC, `organizer_id` ASC);

CREATE INDEX `index5` ON `contest` (`id` ASC, `organizer_id` ASC);


-- -----------------------------------------------------
-- Table `comp_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comp_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `color` VARCHAR(7) NULL,
  `time_begin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `time_end` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comp_class_1`
    FOREIGN KEY (`contest_id` , `organizer_id`)
    REFERENCES `contest` (`id` , `organizer_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `index3` ON `comp_class` (`id` ASC, `contest_id` ASC);

CREATE INDEX `fk_comp_class_1_idx` ON `comp_class` (`contest_id` ASC, `organizer_id` ASC);


-- -----------------------------------------------------
-- Table `contender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `registration_code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(64) NULL,
  `class_id` INT NULL,
  `entered` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `disqualified` TINYINT(1) NOT NULL DEFAULT 0,
  `final_placing` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contender_1`
    FOREIGN KEY (`class_id` , `contest_id`)
    REFERENCES `comp_class` (`id` , `contest_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_contender_2`
    FOREIGN KEY (`contest_id` , `organizer_id`)
    REFERENCES `contest` (`id` , `organizer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_contender_1_idx` ON `contender` (`class_id` ASC, `contest_id` ASC);

CREATE UNIQUE INDEX `registration_code_UNIQUE` ON `contender` (`registration_code` ASC);

CREATE INDEX `fk_contender_2_idx` ON `contender` (`contest_id` ASC, `organizer_id` ASC);

CREATE INDEX `index5` ON `contender` (`id` ASC, `organizer_id` ASC, `contest_id` ASC);


-- -----------------------------------------------------
-- Table `color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rgb_primary` VARCHAR(7) NOT NULL,
  `rgb_secondary` VARCHAR(7) NULL,
  `shared` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_color_1`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `organizer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `name_UNIQUE` ON `color` (`name` ASC, `organizer_id` ASC);

CREATE INDEX `fk_color_1` ON `color` (`organizer_id` ASC);


-- -----------------------------------------------------
-- Table `problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `problem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `number` INT NOT NULL,
  `color_id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `points` INT NOT NULL,
  `flash_bonus` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_problem_1`
    FOREIGN KEY (`contest_id` , `organizer_id`)
    REFERENCES `contest` (`id` , `organizer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_problem_2`
    FOREIGN KEY (`color_id`)
    REFERENCES `color` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_problem_1_idx` ON `problem` (`contest_id` ASC, `organizer_id` ASC);

CREATE UNIQUE INDEX `index3` ON `problem` (`number` ASC, `contest_id` ASC);

CREATE INDEX `fk_problem_2_idx` ON `problem` (`color_id` ASC);

CREATE INDEX `index5` ON `problem` (`id` ASC, `organizer_id` ASC, `contest_id` ASC);


-- -----------------------------------------------------
-- Table `tick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tick` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `contender_id` INT NOT NULL,
  `problem_id` INT NOT NULL,
  `flash` TINYINT(1) NOT NULL DEFAULT 0,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tick_1`
    FOREIGN KEY (`problem_id` , `organizer_id` , `contest_id`)
    REFERENCES `problem` (`id` , `organizer_id` , `contest_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tick_2`
    FOREIGN KEY (`contender_id` , `organizer_id` , `contest_id`)
    REFERENCES `contender` (`id` , `organizer_id` , `contest_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_tick_1_idx` ON `tick` (`problem_id` ASC, `organizer_id` ASC, `contest_id` ASC);

CREATE INDEX `fk_tick_2_idx` ON `tick` (`contender_id` ASC, `organizer_id` ASC, `contest_id` ASC);

CREATE UNIQUE INDEX `index4` ON `tick` (`contender_id` ASC, `problem_id` ASC);


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `username_UNIQUE` ON `user` (`username` ASC);


-- -----------------------------------------------------
-- Table `user_organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_organizer` (
  `user_id` INT NOT NULL,
  `organizer_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `organizer_id`),
  CONSTRAINT `fk_user_organizer_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_user_organizer_2`
    FOREIGN KEY (`organizer_id`)
    REFERENCES `organizer` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_user_organizer_2_idx` ON `user_organizer` (`organizer_id` ASC);


-- -----------------------------------------------------
-- Table `raffle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raffle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_raffle_1`
    FOREIGN KEY (`contest_id` , `organizer_id`)
    REFERENCES `contest` (`id` , `organizer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_raffle_1_idx` ON `raffle` (`contest_id` ASC, `organizer_id` ASC);

CREATE INDEX `index3` ON `raffle` (`id` ASC, `organizer_id` ASC);


-- -----------------------------------------------------
-- Table `raffle_winner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raffle_winner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organizer_id` INT NOT NULL,
  `raffle_id` INT NOT NULL,
  `contender_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_raffle_winner_1`
    FOREIGN KEY (`raffle_id` , `organizer_id`)
    REFERENCES `raffle` (`id` , `organizer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_raffle_winner_2`
    FOREIGN KEY (`contender_id` , `organizer_id`)
    REFERENCES `contender` (`id` , `organizer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_raffle_winner_1_idx` ON `raffle_winner` (`raffle_id` ASC, `organizer_id` ASC);

CREATE INDEX `fk_raffle_winner_2_idx` ON `raffle_winner` (`contender_id` ASC, `organizer_id` ASC);

CREATE UNIQUE INDEX `index4` ON `raffle_winner` (`raffle_id` ASC, `contender_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
