jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          npm install
          git checkout -- package-lock.json
        working-directory: web
      - run: |
          npm install
          git checkout -- package-lock.json
        working-directory: admin
      - run: |
          ./gradlew clean test bootJar
        shell: bash
        working-directory: backend

on:
  pull_request:
  merge_group:

